# Generated by Django 5.0.6 on 2025-11-26 01:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Area de cobertura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Area de Entrega',
                'verbose_name_plural': 'Areas de Entrega',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Endereco de Coleta')),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Endereco de Entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_transit', 'Em transito'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('deadline', models.DateTimeField(verbose_name='Prazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ordem de Entrega',
                'verbose_name_plural': 'Ordens de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('capacity_kg', models.PositiveIntegerField(verbose_name='Capacidade (kg)')),
                ('type', models.CharField(choices=[('truck', 'Caminhao'), ('van', 'Van'), ('car', 'Carro'), ('motorcycle', 'Moto')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='CNH')),
                ('current_status', models.CharField(choices=[('available', 'Disponivel'), ('on_route', 'Em rota'), ('unavailable', 'Indisponivel')], default='available', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['user__username'],
            },
        ),
    ]
