# Generated by Django 5.0.6 on 2025-12-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_garage"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="garage",
            name="street_number",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Numero"),
        ),
        migrations.AlterField(
            model_name="garage",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Endereco"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="garage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="logistics.garage",
                verbose_name="Garagem",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/", verbose_name="Imagem"),
        ),
    ]
