# Generated by Django 5.0.6 on 2025-12-02 00:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_garage_address_changes_vehicle_garage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome da rota")),
                (
                    "start_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Origem"
                    ),
                ),
                (
                    "end_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Destino"
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distancia (km)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planejada"),
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluida"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="logistics.vehicle",
                        verbose_name="Veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rota",
                "verbose_name_plural": "Rotas",
                "ordering": ["-created_at"],
            },
        ),
    ]
