# Generated by Django 5.0.6 on 2025-12-02 00:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326, verbose_name="Ultima posicao"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponivel"),
                    ("in_transit", "Em transito"),
                    ("maintenance", "Manutencao"),
                ],
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
