# Generated by Django 5.0.6 on 2025-12-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_vehicle_status_last_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="logistics.driver",
                verbose_name="Motorista",
            ),
        ),
    ]
