# Generated by Django 5.0.6 on 2025-12-02 00:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0006_route_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="logistics.driver",
                verbose_name="Motorista",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="logistics.vehicle",
                verbose_name="Veiculo",
            ),
        ),
    ]
